/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package It17103664;

import common.Add_Tag;
import common.Add_student_group;
import IT17116770.Add_Subject;
import IT17116770.Add_lecture;
import IT17116770.Add_new_sesison;
import IT17116770.Main_Page;
import IT17116770.Session_management;


public class SessionManage extends javax.swing.JFrame {

    /**
     * Creates new form SessionManage
     */
    public SessionManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addbox = new javax.swing.JButton();
        roombox = new javax.swing.JButton();
        roombox1 = new javax.swing.JButton();
        addbox1 = new javax.swing.JButton();
        roombox2 = new javax.swing.JButton();
        roombox3 = new javax.swing.JButton();
        addbox2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addbox.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        addbox.setText("Add Work Day");
        addbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addboxActionPerformed(evt);
            }
        });

        roombox.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        roombox.setText("Add  Rooms");
        roombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomboxActionPerformed(evt);
            }
        });

        roombox1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        roombox1.setText("Add  Tag");
        roombox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roombox1ActionPerformed(evt);
            }
        });

        addbox1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        addbox1.setText("Add Session");
        addbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbox1ActionPerformed(evt);
            }
        });

        roombox2.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        roombox2.setText("Add  Subject");
        roombox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roombox2ActionPerformed(evt);
            }
        });

        roombox3.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        roombox3.setText("Add  Lecture");
        roombox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roombox3ActionPerformed(evt);
            }
        });

        addbox2.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        addbox2.setText("Add Group");
        addbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add session support details");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addbox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roombox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roombox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roombox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roombox3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(addbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(136, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roombox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roombox1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roombox3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roombox2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomboxActionPerformed
        Add_Room r1 = new Add_Room();
        r1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_roomboxActionPerformed

    private void addboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addboxActionPerformed
        Addworks s1 = new Addworks();
        s1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_addboxActionPerformed

    private void roombox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roombox1ActionPerformed
        // TODO add your handling code here:
         Add_Tag m1 = new Add_Tag();
      m1.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_roombox1ActionPerformed

    private void addbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbox1ActionPerformed
      Add_new_sesison m1 = new Add_new_sesison();
      m1.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_addbox1ActionPerformed

    private void roombox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roombox2ActionPerformed
      Add_Subject m1 = new Add_Subject();
      m1.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_roombox2ActionPerformed

    private void roombox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roombox3ActionPerformed
         Add_lecture m1 = new  Add_lecture();
      m1.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_roombox3ActionPerformed

    private void addbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbox2ActionPerformed
      Add_student_group m1 = new Add_student_group();
      m1.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_addbox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Main_Page m1 = new Main_Page();
      m1.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SessionManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SessionManage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbox;
    private javax.swing.JButton addbox1;
    private javax.swing.JButton addbox2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton roombox;
    private javax.swing.JButton roombox1;
    private javax.swing.JButton roombox2;
    private javax.swing.JButton roombox3;
    // End of variables declaration//GEN-END:variables

    private static class addbox {

        public addbox() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
