/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import code.DBconnect;
import com.mysql.cj.protocol.Resultset;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author DELL
 */
public class Registratio extends javax.swing.JFrame {

    PreparedStatement pst=null;
    Connection con = null;
    Resultset rs = null;
    
    public Registratio(){
    
        con = DBconnect.connect();
        initComponents();
        tableload();
    }
    
    public void tableload()
    {
        try {
            String sql = "SELECT  ID,LecturerName,EmployeeID,faculty,Department,Center,Building,Level,Rank FROM Lecturer";
            pst = con.prepareStatement(sql);
            rs = (Resultset) pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel((ResultSet) rs));
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtempid = new javax.swing.JTextField();
        txtrank = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        combofaculty = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        combodept = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        combocenter = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        combobuldi = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        combolevel = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lecturer Registration");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel2.setText("Lecturer name");

        jLabel3.setText("Employee ID");

        jLabel4.setText("Faculty");

        jLabel5.setText("Rank");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtempid.setMinimumSize(new java.awt.Dimension(6, 6));
        txtempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempidActionPerformed(evt);
            }
        });

        txtrank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrankActionPerformed(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        combofaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Engineering", "Business", "Nursing", "Hotel" }));
        combofaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combofacultyActionPerformed(evt);
            }
        });

        jLabel6.setText("Department");

        combodept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "Business" }));
        combodept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodeptActionPerformed(evt);
            }
        });

        jLabel7.setText("Center");

        combocenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malabe", "kollupitiya" }));
        combocenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocenterActionPerformed(evt);
            }
        });

        jLabel8.setText("Building");

        combobuldi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "Business", "Engineering" }));
        combobuldi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobuldiActionPerformed(evt);
            }
        });

        jLabel9.setText("Level");

        combolevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor - 1", "Assistant professor - 2", "Senior Lecturer(HG) - 3", "Senior Lecturer - 4", "Lecturer - 5", "Assistant Lecturer - 6" }));

        jLabel10.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addbutton)
                        .addGap(49, 49, 49)
                        .addComponent(jButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id)
                            .addComponent(txtrank, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtname)
                                .addComponent(txtempid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combofaculty, 0, 244, Short.MAX_VALUE)
                                .addComponent(combodept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combocenter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combobuldi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combolevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(id))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combofaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(combodept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(combocenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(combobuldi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(combolevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtrank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Emp.ID", "Faculty", "Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combofacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combofacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combofacultyActionPerformed

    private void txtrankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrankActionPerformed

                Connection con1;
                PreparedStatement insert;
    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
                
        String LecturerName = txtname.getText();
        String EmployeeID = txtempid.getText();
        String faculty = (String) combofaculty.getSelectedItem();
        String Department = (String) combodept.getSelectedItem();
        String Center = (String) combocenter.getSelectedItem();
        String Building = (String) combobuldi.getSelectedItem();
        String Level = (String) combolevel.getSelectedItem();
        
        
        String Rank = txtrank.getText();
        
        try {
             String sql = "INSERT INTO Lecturer(LecturerName,EmployeeID,faculty,Department,Center,Building,Level,Rank) VALUES ('"+LecturerName+"','"+EmployeeID+"','"+faculty+"','"+Department+"','"+Center+"','"+Building+"','" +Level+"','" +Rank+"')";
        
        pst = con.prepareStatement(sql);
        pst.execute();
        
        } catch (Exception e) {
            System.out.println(e);
        }
            
            
        tableload();
            
             
                
                
                
                
    }//GEN-LAST:event_addbuttonActionPerformed

    private void combodeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combodeptActionPerformed

    private void combocenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combocenterActionPerformed

    private void combobuldiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobuldiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobuldiActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
       
    }//GEN-LAST:event_txtempidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           int x = JOptionPane.showConfirmDialog(null, "Do you really want to update");
        
        if(x==0)
        {
            String ID = id.getText();
            String LecturerName = txtname.getText();
            String EmployeeID = txtempid.getText();
            String faculty = (String) combofaculty.getSelectedItem();
            String Department = (String) combodept.getSelectedItem();
            String Center = (String) combocenter.getSelectedItem();
            String Building = (String) combobuldi.getSelectedItem();
            String Level = (String) combolevel.getSelectedItem();
            
            try {
            String sql = "UPDATE Lecturer SET LecturerName = '" + LecturerName +"', EmployeeID = '"+ EmployeeID +"', faculty = '"+ faculty +"', Department = '"+ Department +"', Center = '"+ Center +"', Building = '"+ Building +"', Level = '"+ Level +"'  WHERE ID = '"+ ID +"' ";
            
             pst = con.prepareStatement(sql);
             
             pst.execute();
             
             tableload();
             
        } catch (Exception e) {
            System.out.println(e);
        }
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int r = jTable1.getSelectedRow();
        String ID = jTable1.getValueAt(r, 0).toString();
        String LecturerName = jTable1.getValueAt(r, 1).toString();
        String EmployeeID = jTable1.getValueAt(r, 2).toString();
        String faculty = jTable1.getValueAt(r, 3).toString();
        String Department = (String) jTable1.getValueAt(r, 4);
        String Center = (String) jTable1.getValueAt(r, 5);
        String Building = jTable1.getValueAt(r, 6).toString();
        String Level = jTable1.getValueAt(r, 7).toString();
        String Rank = jTable1.getValueAt(r, 8).toString();
        
        
        id.setText(ID);
        txtname.setText(LecturerName);
        txtempid.setText(EmployeeID);
        combofaculty.setSelectedItem(faculty);
        combodept.setSelectedItem(Department);
        combocenter.setSelectedItem(Center);
        combobuldi.setSelectedItem(Building);
        combolevel.setSelectedItem(Level);
        txtrank.setText(Rank);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this");
        
        if(x==0)
        {
            String ID = txtname.getText();
            
            try {
                String sql = "DELETE from Lecturer where LecturerName = '" + ID + "'"; 
                pst = con.prepareStatement(sql);
                pst.execute();
                tableload();
            } catch (SQLException e) {
                
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registratio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registratio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registratio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registratio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registratio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JComboBox<String> combobuldi;
    private javax.swing.JComboBox<String> combocenter;
    private javax.swing.JComboBox<String> combodept;
    private javax.swing.JComboBox<String> combofaculty;
    private javax.swing.JComboBox<String> combolevel;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtrank;
    // End of variables declaration//GEN-END:variables
}
